"""empty message

Revision ID: 799ea842aaf0
Revises: 2b472242533f
Create Date: 2024-12-05 08:51:35.104888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799ea842aaf0'
down_revision = '2b472242533f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron', sa.Column('unique', sa.Boolean(), nullable=False))
    op.add_column('cron', sa.Column('max_tries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cron', 'max_tries')
    op.drop_column('cron', 'unique')
    # ### end Alembic commands ###
