"""empty message

Revision ID: 4fd7f43e6fe5
Revises: 8d0bcfcb6522
Create Date: 2024-12-17 20:18:48.641928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd7f43e6fe5'
down_revision = '8d0bcfcb6522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron', sa.Column('year', sa.String(), server_default='*', nullable=True))
    op.add_column('cron', sa.Column('week', sa.String(), server_default='*', nullable=True))
    op.add_column('cron', sa.Column('day_of_week', sa.String(), server_default='*', nullable=True))
    op.add_column('cron', sa.Column('start_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('cron', sa.Column('end_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('cron', sa.Column('timezone', sa.String(), server_default='Europe/Moscow', nullable=False))
    op.add_column('cron', sa.Column('jitter', sa.Integer(), nullable=True))
    op.alter_column('cron', 'month',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cron', 'day',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cron', 'hour',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cron', 'minute',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cron', 'second',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('cron', 'weekday')
    op.drop_column('cron', 'max_tries')
    op.drop_column('cron', 'unique')
    op.drop_column('cron', 'microsecond')
    op.drop_column('cron', 'run_at_startup')
    op.drop_column('cron', 'keep_result')
    op.drop_column('cron', 'keep_result_forever')
    op.drop_column('cron', 'timeout')
    op.add_column('emitter', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emitter', 'name')
    op.add_column('cron', sa.Column('timeout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cron', sa.Column('keep_result_forever', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('cron', sa.Column('keep_result', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cron', sa.Column('run_at_startup', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('cron', sa.Column('microsecond', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cron', sa.Column('unique', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('cron', sa.Column('max_tries', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cron', sa.Column('weekday', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('cron', 'second',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cron', 'minute',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cron', 'hour',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cron', 'day',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cron', 'month',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('cron', 'jitter')
    op.drop_column('cron', 'timezone')
    op.drop_column('cron', 'end_date')
    op.drop_column('cron', 'start_date')
    op.drop_column('cron', 'day_of_week')
    op.drop_column('cron', 'week')
    op.drop_column('cron', 'year')
    # ### end Alembic commands ###
