"""empty message

Revision ID: 550981edf305
Revises: 52d76e03eff3
Create Date: 2024-11-26 17:53:36.944294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550981edf305'
down_revision = '52d76e03eff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
