"""empty message

Revision ID: 12b12e74da02
Revises: 39515ded9d72
Create Date: 2024-12-05 16:23:02.351616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b12e74da02'
down_revision = '39515ded9d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
