"""empty message

Revision ID: 2b472242533f
Revises: 8fdd1c9aefbd
Create Date: 2024-12-05 08:50:49.798118

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = '2b472242533f'
down_revision = '8fdd1c9aefbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.String(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('second', sa.Integer(), nullable=True),
    sa.Column('microsecond', sa.Integer(), nullable=False),
    sa.Column('run_at_startup', sa.Boolean(), nullable=False),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('keep_result', sa.Float(), nullable=True),
    sa.Column('keep_result_forever', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cron'))
    )
    op.create_table('emitter',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('cron_id', app.models.base.UUID(), nullable=False),
    sa.Column('message_id', app.models.base.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['cron_id'], ['cron.id'], name=op.f('fk_emitter_cron_id_cron')),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_emitter_message_id_message')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emitter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emitter')
    op.drop_table('cron')
    # ### end Alembic commands ###
