"""empty message

Revision ID: f1684a5fe837
Revises: d7ab4fe97448
Create Date: 2024-11-20 10:01:16.631375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1684a5fe837'
down_revision = 'd7ab4fe97448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_variables', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('bot_variables', 'json')
    op.add_column('channel_variables', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('channel_variables', 'json')
    op.add_column('session_variables', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('session_variables', 'json')
    op.add_column('user_variables', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('user_variables', 'json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_variables', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user_variables', 'data')
    op.add_column('session_variables', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('session_variables', 'data')
    op.add_column('channel_variables', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('channel_variables', 'data')
    op.add_column('bot_variables', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('bot_variables', 'data')
    # ### end Alembic commands ###
