"""empty message

Revision ID: a213097e8b75
Revises: 53c3e9bd2022
Create Date: 2024-12-05 12:18:07.433681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a213097e8b75'
down_revision = '53c3e9bd2022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('logs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'logs')
    # ### end Alembic commands ###
