"""empty message

Revision ID: cb3eeb4a6cc6
Revises: c99d858281e3
Create Date: 2024-12-05 10:22:29.844077

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = 'cb3eeb4a6cc6'
down_revision = 'c99d858281e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emitter', sa.Column('step_id', app.models.base.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_emitter_step_id_step'), 'emitter', 'step', ['step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_emitter_step_id_step'), 'emitter', type_='foreignkey')
    op.drop_column('emitter', 'step_id')
    # ### end Alembic commands ###
