"""empty message

Revision ID: 3a32d3c26de6
Revises: c853ef4a04c3
Create Date: 2024-11-15 15:14:00.467871

"""
from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision = '3a32d3c26de6'
down_revision = 'c853ef4a04c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('bot_id', app.models.base.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_step_bot_id_bot'), 'step', 'bot', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_step_bot_id_bot'), 'step', type_='foreignkey')
    op.drop_column('step', 'bot_id')
    # ### end Alembic commands ###
