"""empty message

Revision ID: 7fcf4e591248
Revises: 4fd7f43e6fe5
Create Date: 2024-12-18 10:17:04.547117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcf4e591248'
down_revision = '4fd7f43e6fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emitter', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emitter', 'is_active')
    # ### end Alembic commands ###
