"""empty message

Revision ID: c853ef4a04c3
Revises: 
Create Date: 2024-11-15 15:13:30.320007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.base

# revision identifiers, used by Alembic.
revision = 'c853ef4a04c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('request_url', sa.String(), nullable=False),
    sa.Column('method', sa.Enum('get', 'post', name='requestmethodtype'), nullable=False),
    sa.Column('headers', sa.String(), nullable=True),
    sa.Column('url_params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request'))
    )
    op.create_table('step',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_step'))
    )
    op.create_table('subscriber',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriber'))
    )
    op.create_table('widget',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('css', sa.String(), nullable=False),
    sa.Column('js', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget'))
    )
    op.create_table('connection_group',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('search_type', sa.Enum('response', 'message', 'code', name='searchtype'), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('request_id', app.models.base.UUID(), nullable=True),
    sa.Column('step_id', app.models.base.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], name=op.f('fk_connection_group_request_id_request')),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], name=op.f('fk_connection_group_step_id_step')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_group'))
    )
    op.create_table('user',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['subscriber.id'], name=op.f('fk_user_id_subscriber')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('bot',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', app.models.base.UUID(), nullable=True),
    sa.Column('first_step_id', app.models.base.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['first_step_id'], ['step.id'], name=op.f('fk_bot_first_step_id_step')),
    sa.ForeignKeyConstraint(['id'], ['subscriber.id'], name=op.f('fk_bot_id_subscriber')),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_bot_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot'))
    )
    op.create_table('connection',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('group_id', app.models.base.UUID(), nullable=False),
    sa.Column('rules', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('plugins', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('filters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('next_step_id', app.models.base.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['connection_group.id'], name=op.f('fk_connection_group_id_connection_group')),
    sa.ForeignKeyConstraint(['next_step_id'], ['step.id'], name=op.f('fk_connection_next_step_id_step')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection'))
    )
    op.create_table('user_variables',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_user_variables_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_variables'))
    )
    op.create_table('bot_variables',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bot.id'], name=op.f('fk_bot_variables_id_bot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_variables'))
    )
    op.create_table('channel',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('owner_id', app.models.base.UUID(), nullable=True),
    sa.Column('default_bot_id', app.models.base.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['default_bot_id'], ['bot.id'], name=op.f('fk_channel_default_bot_id_bot')),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_channel_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel'))
    )
    op.create_index(op.f('ix_channel_name'), 'channel', ['name'], unique=False)
    op.create_table('channel_variables',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['channel.id'], name=op.f('fk_channel_variables_id_channel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_variables'))
    )
    op.create_table('message',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('channel_id', app.models.base.UUID(), nullable=True),
    sa.Column('recipient_id', app.models.base.UUID(), nullable=True),
    sa.Column('sender_id', app.models.base.UUID(), nullable=True),
    sa.Column('step_id', app.models.base.UUID(), nullable=True),
    sa.Column('widget_id', app.models.base.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_message_channel_id_channel')),
    sa.ForeignKeyConstraint(['recipient_id'], ['subscriber.id'], name=op.f('fk_message_recipient_id_subscriber')),
    sa.ForeignKeyConstraint(['sender_id'], ['subscriber.id'], name=op.f('fk_message_sender_id_subscriber')),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], name=op.f('fk_message_step_id_step')),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], name=op.f('fk_message_widget_id_widget')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_table('session',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('user_id', app.models.base.UUID(), nullable=False),
    sa.Column('bot_id', app.models.base.UUID(), nullable=False),
    sa.Column('channel_id', app.models.base.UUID(), nullable=False),
    sa.Column('step_id', app.models.base.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], name=op.f('fk_session_bot_id_bot')),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_session_channel_id_channel')),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], name=op.f('fk_session_step_id_step')),
    sa.ForeignKeyConstraint(['user_id'], ['subscriber.id'], name=op.f('fk_session_user_id_subscriber')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session')),
    sa.UniqueConstraint('user_id', 'bot_id', 'channel_id', name=op.f('uq_session_user_id'))
    )
    op.create_table('subscribers_table',
    sa.Column('subscriber_id', app.models.base.UUID(), nullable=False),
    sa.Column('channel_id', app.models.base.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_subscribers_table_channel_id_channel')),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.id'], name=op.f('fk_subscribers_table_subscriber_id_subscriber')),
    sa.PrimaryKeyConstraint('subscriber_id', 'channel_id', name=op.f('pk_subscribers_table'))
    )
    op.create_table('attachment',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file', app.models.attachment.FileType(), nullable=True),
    sa.Column('message_id', app.models.base.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_attachment_message_id_message')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    op.create_table('session_variables',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['session.id'], name=op.f('fk_session_variables_id_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_variables'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_variables')
    op.drop_table('attachment')
    op.drop_table('subscribers_table')
    op.drop_table('session')
    op.drop_table('message')
    op.drop_table('channel_variables')
    op.drop_index(op.f('ix_channel_name'), table_name='channel')
    op.drop_table('channel')
    op.drop_table('bot_variables')
    op.drop_table('user_variables')
    op.drop_table('connection')
    op.drop_table('bot')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('connection_group')
    op.drop_table('widget')
    op.drop_table('subscriber')
    op.drop_table('step')
    op.drop_table('request')
    # ### end Alembic commands ###
