"""empty message

Revision ID: 3240e6640f4f
Revises: 12b12e74da02
Create Date: 2024-12-05 16:23:14.415630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3240e6640f4f'
down_revision = '12b12e74da02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'data')
    # ### end Alembic commands ###
