"""empty message

Revision ID: 8fdd1c9aefbd
Revises: 08b45b6a9e20
Create Date: 2024-12-05 08:07:32.949842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fdd1c9aefbd'
down_revision = '08b45b6a9e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'data')
    # ### end Alembic commands ###
