"""empty message

Revision ID: 53c3e9bd2022
Revises: cb3eeb4a6cc6
Create Date: 2024-12-05 10:32:58.422855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c3e9bd2022'
down_revision = 'cb3eeb4a6cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cron', 'weekday',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cron', 'weekday',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
