"""empty message

Revision ID: 39515ded9d72
Revises: f5f534d7a870
Create Date: 2024-12-05 16:17:03.522632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39515ded9d72'
down_revision = 'f5f534d7a870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
