"""empty message

Revision ID: 127add820876
Revises: 3ed83e51d86a
Create Date: 2025-09-18 08:41:43.369043

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = '127add820876'
down_revision = '3ed83e51d86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('owner_id', app.models.base.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_request_owner_id_user'), 'request', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_request_owner_id_user'), 'request', type_='foreignkey')
    op.drop_column('request', 'owner_id')
    # ### end Alembic commands ###
