"""empty message

Revision ID: d1e28244d15d
Revises: d2a0193b540c
Create Date: 2025-02-13 09:31:08.721990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.base

# revision identifiers, used by Alembic.
revision = 'd1e28244d15d'
down_revision = 'd2a0193b540c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_user',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['subscriber.id'], name=op.f('fk_anonymous_user_id_subscriber')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anonymous_user'))
    )
    op.create_table('anonymous_user_variables',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['anonymous_user.id'], name=op.f('fk_anonymous_user_variables_id_anonymous_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anonymous_user_variables'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anonymous_user_variables')
    op.drop_table('anonymous_user')
    # ### end Alembic commands ###
