"""empty message

Revision ID: e7b0cbbf8acd
Revises: 5a2bc32da0da
Create Date: 2025-02-12 13:40:35.802663

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = 'e7b0cbbf8acd'
down_revision = '5a2bc32da0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emitter', sa.Column('bot_id', app.models.base.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_emitter_bot_id_bot'), 'emitter', 'bot', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_emitter_bot_id_bot'), 'emitter', type_='foreignkey')
    op.drop_column('emitter', 'bot_id')
    # ### end Alembic commands ###
