"""empty message

Revision ID: ee779614144c
Revises: 509b4a8bf552
Create Date: 2025-06-04 09:13:42.715359

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = 'ee779614144c'
down_revision = '509b4a8bf552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('template_instance_id', app.models.base.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_step_template_instance_id_template_instance'), 'step', 'template_instance', ['template_instance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_step_template_instance_id_template_instance'), 'step', type_='foreignkey')
    op.drop_column('step', 'template_instance_id')
    # ### end Alembic commands ###
