"""empty message

Revision ID: 4c9a867215bb
Revises: ee779614144c
Create Date: 2025-06-15 08:58:26.079587

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = '4c9a867215bb'
down_revision = 'ee779614144c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('owner_id', app.models.base.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_template_owner_id_user'), 'template', 'user', ['owner_id'], ['id'])
    op.add_column('template_instance', sa.Column('template_id', app.models.base.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_template_instance_template_id_template'), 'template_instance', 'template', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_template_instance_template_id_template'), 'template_instance', type_='foreignkey')
    op.drop_column('template_instance', 'template_id')
    op.drop_constraint(op.f('fk_template_owner_id_user'), 'template', type_='foreignkey')
    op.drop_column('template', 'owner_id')
    # ### end Alembic commands ###
