"""empty message

Revision ID: 468d32916b7b
Revises: 127add820876
Create Date: 2025-10-08 13:39:03.510181

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = '468d32916b7b'
down_revision = '127add820876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget', sa.Column('owner_id', app.models.base.UUID(), nullable=True))
    op.add_column('widget', sa.Column('is_render', sa.Boolean(), server_default='FALSE', nullable=True, comment='False = шаблон, True = готовый виджет'))
    op.execute("UPDATE widget SET is_render = false WHERE is_render IS NULL")
    op.alter_column('widget', 'is_render', nullable=False, server_default='FALSE')
    op.add_column('widget', sa.Column('parent_widget_id', app.models.base.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_widget_owner_id_user'), 'widget', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('fk_widget_parent_widget_id_widget'), 'widget', 'widget', ['parent_widget_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_widget_parent_widget_id_widget'), 'widget', type_='foreignkey')
    op.drop_constraint(op.f('fk_widget_owner_id_user'), 'widget', type_='foreignkey')
    op.drop_column('widget', 'parent_widget_id')
    op.drop_column('widget', 'is_render')
    op.drop_column('widget', 'owner_id')
    # ### end Alembic commands ###
