"""empty message

Revision ID: 1b7a8e8a574f
Revises: 4c9a867215bb
Create Date: 2025-06-16 13:43:35.459124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7a8e8a574f'
down_revision = '4c9a867215bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('template_instance', 'template_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('fk_template_instance_template_id_template', 'template_instance', type_='foreignkey')
    op.create_foreign_key(op.f('fk_template_instance_template_id_template'), 'template_instance', 'template', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_template_instance_template_id_template'), 'template_instance', type_='foreignkey')
    op.create_foreign_key('fk_template_instance_template_id_template', 'template_instance', 'template', ['template_id'], ['id'])
    op.alter_column('template_instance', 'template_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
