"""empty message

Revision ID: 8eeedd8089b3
Revises: 85361f36c87d
Create Date: 2025-05-06 15:35:11.643400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eeedd8089b3'
down_revision = '85361f36c87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'config')
    # ### end Alembic commands ###
