"""empty message

Revision ID: 3ed83e51d86a
Revises: 20250819_credentials_default_idx
Create Date: 2025-09-17 12:07:29.294510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed83e51d86a'
down_revision = '20250819_credentials_default_idx'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cred_bot_provider_strategy', 'credentials_entity', type_='unique')
    op.drop_index('uq_cred_default_per_provider', table_name='credentials_entity', postgresql_where='(is_default = true)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_cred_default_per_provider', 'credentials_entity', ['bot_id', 'provider', 'strategy'], unique=True, postgresql_where='(is_default = true)')
    op.create_unique_constraint('uq_cred_bot_provider_strategy', 'credentials_entity', ['bot_id', 'provider', 'strategy'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
