"""empty message

Revision ID: 44e6dea373c5
Revises: b2c3742d4c0d
Create Date: 2025-01-29 17:36:56.012052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e6dea373c5'
down_revision = 'b2c3742d4c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emitter', sa.Column('pos_x', sa.Integer(), server_default='0', nullable=False))
    op.add_column('emitter', sa.Column('pos_y', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emitter', 'pos_y')
    op.drop_column('emitter', 'pos_x')
    # ### end Alembic commands ###
