"""empty message

Revision ID: 5153af8056bd
Revises: 7fcf4e591248
Create Date: 2025-01-13 08:46:53.465515

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = '5153af8056bd'
down_revision = '7fcf4e591248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_group', sa.Column('bot_id', app.models.base.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_connection_group_bot_id_bot'), 'connection_group', 'bot', ['bot_id'], ['id'])
    op.drop_column('cron', 'week')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron', sa.Column('week', sa.VARCHAR(), server_default=sa.text("'*'::character varying"), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_connection_group_bot_id_bot'), 'connection_group', type_='foreignkey')
    op.drop_column('connection_group', 'bot_id')
    # ### end Alembic commands ###
