"""empty message

Revision ID: 11948e12933c
Revises: 0892f4b83711
Create Date: 2025-03-24 15:44:53.714401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11948e12933c'
down_revision = '0892f4b83711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emitter', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('request', sa.Column('json_field', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'json_field')
    op.alter_column('emitter', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
