"""empty message

Revision ID: d2a0193b540c
Revises: e7b0cbbf8acd
Create Date: 2025-02-12 13:42:54.179333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a0193b540c'
down_revision = 'e7b0cbbf8acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_emitter_step_id_step', 'emitter', type_='foreignkey')
    op.drop_column('emitter', 'step_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emitter', sa.Column('step_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_emitter_step_id_step', 'emitter', 'step', ['step_id'], ['id'])
    # ### end Alembic commands ###
