"""empty message

Revision ID: f3c81863de86
Revises: f91e716a4b7e
Create Date: 2025-01-27 12:59:36.180876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c81863de86'
down_revision = 'f91e716a4b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('pos_x', sa.Integer(), server_default='0', nullable=False))
    op.add_column('step', sa.Column('pos_y', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'pos_y')
    op.drop_column('step', 'pos_x')
    # ### end Alembic commands ###
