"""empty message

Revision ID: 9da8b36cb510
Revises: 5153af8056bd
Create Date: 2025-01-21 19:36:43.079829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da8b36cb510'
down_revision = '5153af8056bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connection_group', 'bot_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connection_group', 'bot_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
