"""empty message

Revision ID: b2c3742d4c0d
Revises: f3c81863de86
Create Date: 2025-01-27 13:00:31.341407

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = 'b2c3742d4c0d'
down_revision = 'f3c81863de86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('bot_id', app.models.base.UUID(), nullable=False),
    sa.Column('step_id', app.models.base.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('pos_x', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pos_y', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], name=op.f('fk_note_bot_id_bot')),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], name=op.f('fk_note_step_id_step')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
