"""empty message

Revision ID: 52d76e03eff3
Revises: f1684a5fe837
Create Date: 2024-11-26 17:32:53.774526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52d76e03eff3'
down_revision = 'f1684a5fe837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'attachments')
    # ### end Alembic commands ###
