"""empty message

Revision ID: 8d0bcfcb6522
Revises: 3240e6640f4f
Create Date: 2024-12-16 10:54:31.367363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0bcfcb6522'
down_revision = '3240e6640f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('connection_group', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('step', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'description')
    op.drop_column('connection_group', 'priority')
    op.drop_column('connection', 'priority')
    # ### end Alembic commands ###
