"""empty message

Revision ID: d7ab4fe97448
Revises: 3a32d3c26de6
Create Date: 2024-11-18 03:49:11.192069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7ab4fe97448'
down_revision = '3a32d3c26de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'variables')
    op.drop_column('connection', 'plugins')
    op.add_column('connection_group', sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection_group', 'variables')
    op.add_column('connection', sa.Column('plugins', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('connection', sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
