"""empty message

Revision ID: 85361f36c87d
Revises: a9fb7e4bd7b8
Create Date: 2025-05-05 14:30:27.727313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85361f36c87d'
down_revision = 'a9fb7e4bd7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_session_user_id', 'session', type_='unique')
    op.create_index('ix_session_user_id_bot_id_channel_id', 'session', ['user_id', 'bot_id', 'channel_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_user_id_bot_id_channel_id', table_name='session')
    op.create_unique_constraint('uq_session_user_id', 'session', ['user_id', 'bot_id', 'channel_id'])
    # ### end Alembic commands ###
