"""empty message

Revision ID: eb159fd72607
Revises: 1f614bed3811
Create Date: 2025-07-03 11:23:06.884363

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = 'eb159fd72607'
down_revision = '1f614bed3811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('bot_id', app.models.base.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_template_bot_id_bot'), 'template', 'bot', ['bot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_template_bot_id_bot'), 'template', type_='foreignkey')
    op.drop_column('template', 'bot_id')
    # ### end Alembic commands ###
