"""empty message

Revision ID: 5e59027a3109
Revises: 11948e12933c
Create Date: 2025-03-26 09:19:58.093932

"""
from alembic import op
import sqlalchemy as sa
import app.models.base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e59027a3109'
down_revision = '11948e12933c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enums
    op.execute('CREATE TYPE roletype AS ENUM (\'ADMIN\', \'DEVELOPER\', \'USER\')')

    op.create_table('user_bot_access',
    sa.Column('user_id', app.models.base.UUID(), nullable=False),
    sa.Column('bot_id', app.models.base.UUID(), nullable=False),
    sa.Column('access_type', postgresql.ENUM('VIEWER', 'EDITOR', 'NO_ACCESS', name='accesstype'), server_default='NO_ACCESS', nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], name=op.f('fk_user_bot_access_bot_id_bot')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_bot_access_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'bot_id', name=op.f('pk_user_bot_access'))
    )
    op.add_column('user', sa.Column('role', postgresql.ENUM('ADMIN', 'DEVELOPER', 'USER', name='roletype'), server_default='USER', nullable=False))
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    op.drop_table('user_bot_access')
    op.execute('DROP TYPE roletype')
    op.execute('DROP TYPE accesstype')
    # ### end Alembic commands ###
