"""empty message

Revision ID: 458db03e44d0
Revises: eb159fd72607
Create Date: 2025-07-10 12:05:24.872174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '458db03e44d0'
down_revision = 'eb159fd72607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('cache_structure', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'cache_structure')
    # ### end Alembic commands ###
