"""empty message

Revision ID: 0fcb7f51dbc1
Revises: 8eeedd8089b3
Create Date: 2025-05-15 07:57:40.886258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcb7f51dbc1'
down_revision = '8eeedd8089b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('proxies', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'proxies')
    # ### end Alembic commands ###
