"""empty message

Revision ID: 1f614bed3811
Revises: 67a91bfef3a9
Create Date: 2025-06-16 17:00:33.357944

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = '1f614bed3811'
down_revision = '67a91bfef3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_group',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', app.models.base.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_template_group_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_group'))
    )
    op.add_column('template', sa.Column('group_id', app.models.base.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_template_group_id_template_group'), 'template', 'template_group', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_template_group_id_template_group'), 'template', type_='foreignkey')
    op.drop_column('template', 'group_id')
    op.drop_table('template_group')
    # ### end Alembic commands ###
