"""empty message

Revision ID: f91e716a4b7e
Revises: 9da8b36cb510
Create Date: 2025-01-24 17:01:50.283944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91e716a4b7e'
down_revision = '9da8b36cb510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('connection_group', 'step_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connection_group', 'step_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('channel', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
