"""empty message

Revision ID: a9fb7e4bd7b8
Revises: 0bb52266a8de
Create Date: 2025-04-11 07:27:34.846127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fb7e4bd7b8'
down_revision = '0bb52266a8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emitter', sa.Column('needs_message_processing', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emitter', 'needs_message_processing')
    # ### end Alembic commands ###
