"""empty message

Revision ID: 0bb52266a8de
Revises: 5e59027a3109
Create Date: 2025-04-02 16:09:57.561402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb52266a8de'
down_revision = '5e59027a3109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emitter', 'cron_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('emitter', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emitter', 'message_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('emitter', 'cron_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
