"""empty message

Revision ID: e9575db07ca8
Revises: 1b7a8e8a574f
Create Date: 2025-06-16 13:46:33.002031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9575db07ca8'
down_revision = '1b7a8e8a574f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_step_template_instance_id_template_instance', 'step', type_='foreignkey')
    op.create_foreign_key(op.f('fk_step_template_instance_id_template_instance'), 'step', 'template_instance', ['template_instance_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_step_template_instance_id_template_instance'), 'step', type_='foreignkey')
    op.create_foreign_key('fk_step_template_instance_id_template_instance', 'step', 'template_instance', ['template_instance_id'], ['id'])
    # ### end Alembic commands ###
