"""empty message

Revision ID: 67a91bfef3a9
Revises: e9575db07ca8
Create Date: 2025-06-16 14:44:30.751823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a91bfef3a9'
down_revision = 'e9575db07ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('first_step_id', sa.String(), nullable=False))
    op.add_column('template_instance', sa.Column('first_step_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_instance', 'first_step_id')
    op.drop_column('template', 'first_step_id')
    # ### end Alembic commands ###
