"""empty message

Revision ID: c7a29493ed79
Revises: bc5ad8ff984e
Create Date: 2025-08-19 08:57:42.525203

"""
from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision = 'c7a29493ed79'
down_revision = 'bc5ad8ff984e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials_entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('bot_id', app.models.base.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], name=op.f('fk_credentials_entity_bot_id_bot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials_entity')),
    sa.UniqueConstraint('bot_id', 'provider', 'strategy', name='uq_cred_bot_provider_strategy')
    )
    op.create_index('ix_cred_bot', 'credentials_entity', ['bot_id'], unique=False)
    op.create_index('ix_cred_provider', 'credentials_entity', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cred_provider', table_name='credentials_entity')
    op.drop_index('ix_cred_bot', table_name='credentials_entity')
    op.drop_table('credentials_entity')
    # ### end Alembic commands ###
