# coding: utf-8

# flake8: noqa
"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from github_openapi_client.models.author_association import AuthorAssociation
from github_openapi_client.models.auto_merge import AutoMerge
from github_openapi_client.models.basic_error import BasicError
from github_openapi_client.models.link import Link
from github_openapi_client.models.nullable_license_simple import NullableLicenseSimple
from github_openapi_client.models.nullable_milestone import NullableMilestone
from github_openapi_client.models.nullable_simple_user import NullableSimpleUser
from github_openapi_client.models.pull_request import PullRequest
from github_openapi_client.models.pull_request_head import PullRequestHead
from github_openapi_client.models.pull_request_labels_inner import PullRequestLabelsInner
from github_openapi_client.models.pull_request_links import PullRequestLinks
from github_openapi_client.models.pull_request_webhook import PullRequestWebhook
from github_openapi_client.models.pulls_get503_response import PullsGet503Response
from github_openapi_client.models.repository import Repository
from github_openapi_client.models.repository_code_search_index_status import RepositoryCodeSearchIndexStatus
from github_openapi_client.models.repository_permissions import RepositoryPermissions
from github_openapi_client.models.ruleset_version import RulesetVersion
from github_openapi_client.models.ruleset_version_actor import RulesetVersionActor
from github_openapi_client.models.ruleset_version_with_state import RulesetVersionWithState
from github_openapi_client.models.simple_user import SimpleUser
from github_openapi_client.models.team_simple import TeamSimple

